#!/bin/bash

set -e

apt-get update -q
DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends make \
        build-essential \
        libicu-dev

rm -rf /var/lib/apt/lists/*

gem install gitlab-mail_room:${MAILROOM_VERSION} \
        charlock_holmes:0.7.6 \
        redis:4.3.1 \
        redis-namespace:1.6.0 \
        webrick:1.7.0

/build-scripts/cleanup-gems /usr/lib/ruby/gems

DEBIAN_FRONTEND=noninteractive apt-get purge -yq make build-essential libicu-dev
