ARG BUILD_IMAGE=

FROM ${BUILD_IMAGE}

ARG GOMPLATE_VERSION="v3.11.3"
ARG GOMPLATE_SHA256=2c67ef580d2416e82dc2ab8f0c30e1bf372dcd3e8511073df9310d91dc3d5f94

ENV LANG=C.UTF-8
ENV GOMPLATE_SOURCE_URL="https://github.com/hairyhenderson/gomplate/releases/download/$GOMPLATE_VERSION/gomplate_linux-amd64"

COPY scripts/download /scripts/download

RUN mkdir -p /target /assets/usr/local/bin \
    && /scripts/download \
    && mv /target/gomplate /assets/usr/local/bin/gomplate
