#!/bin/bash
DEBIAN_FRONTEND=noninteractive

apt-get update

utilities="ca-certificates curl gpg xz-utils"
tools="build-essential"
dependencies="libpng-dev libpng16-16 libturbojpeg0-dev libturbojpeg0 zlib1g-dev zlib1g libtiff-dev libtiff5"

# Install tools and libaries needed for compilation
apt-get install -q -y --no-install-recommends \
  ${utilities} ${tools} ${dependencies}
