ARG BUILD_IMAGE=

FROM ${BUILD_IMAGE}

ARG DOCUTILS_VERSION=0.16

ADD gitlab-python.tar.gz /
ADD https://gitlab.com/gitlab-org/gitlab/-/raw/master/LICENSE /licenses/GitLab.txt

RUN mkdir /assets \
    && pip3 install --compile docutils==${DOCUTILS_VERSION} \
    && cp -R --parents \
        /usr/local/lib/python3.8/site-packages \
        /usr/local/bin/rst2* \
        /licenses \
        /assets
