# This is a place holder, allowing us to mirror the gitlab-toolbox image to gitlab-task-runner
ARG CI_REGISTRY_IMAGE="registry.gitlab.com/gitlab-org/build/cng"
ARG FROM_IMAGE="$CI_REGISTRY_IMAGE/gitlab-toolbox"
FROM ${FROM_IMAGE}:${COMMIT_REF_SLUG}
