#!/bin/bash

WAIT_FOR_TIMEOUT="${WAIT_FOR_TIMEOUT:-30}"
SLEEP_DURATION="${SLEEP_DURATION:-1}"
BYPASS_SCHEMA_VERSION="${BYPASS_SCHEMA_VERSION:-}"

TMP=$(mktemp)

function checkStatus {
  output=$(registry database migrate status ${CONFIG_DIRECTORY}/${CONFIG_FILENAME} > ${TMP})
  ret=$?

  if [ $ret -eq 0 ]; then
    # successful run, check the output, if we care
    if [ -z "${BYPASS_SCHEMA_VERSION}" ]; then
      check=$(tail -n2 ${TMP} | head -n1 | cut -d'|' -f 2)
      if [ "${check}" == "" ]; then
        ret=2
      fi
    fi
  fi

  return $ret
}

counter=1
until [ $counter -eq $WAIT_FOR_TIMEOUT ]; do
  # if successful, break and move on.
  if checkStatus ; then
    break
  fi
  # otherwise, sleep, increment, and try again.
  sleep $SLEEP_DURATION;
  ((counter++))
done

# `exec` the arguments passed to this script (if any)
exec "$@"
