#!/bin/bash

set -e

GITALY_CONFIG_FILE="${GITALY_CONFIG_FILE:-$CONFIG_TEMPLATE_DIRECTORY/config.toml}"
PRAEFECT_CONFIG_FILE="${PRAEFECT_CONFIG_FILE:-$CONFIG_TEMPLATE_DIRECTORY/config.toml}"

if [ "${USE_GITLAB_LOGGER:-0}" -eq 1 ]; then
    /usr/local/bin/gitlab-logger --json /var/log/gitaly &
elif command -v xtail >/dev/null; then
    xtail /var/log/gitaly &
else
    tail -f /var/log/gitaly/* &
fi

if [ "${USE_PRAEFECT_SERVICE:-0}" -eq 1 ]; then
  echo "Starting Praefect"

  if [ "${PRAEFECT_AUTO_MIGRATE:-1}" -eq 1 ]; then
    echo "Running migrations"
    /usr/local/bin/praefect -config "$PRAEFECT_CONFIG_FILE" sql-migrate
  fi

  exec /usr/local/bin/praefect -config "$PRAEFECT_CONFIG_FILE" >> /var/log/gitaly/praefect.log 2>&1
else
  echo "Starting Gitaly"

  exec /usr/local/bin/gitaly "$GITALY_CONFIG_FILE" >> /var/log/gitaly/gitaly.log 2>&1
fi
