#!/bin/bash

set -e

GITALY_CONFIG_FILE="${GITALY_CONFIG_FILE:-$CONFIG_TEMPLATE_DIRECTORY/config.toml}"

echo "Starting Gitaly"
/usr/local/bin/gitaly "$GITALY_CONFIG_FILE" >> /var/log/gitaly/gitaly.log 2>&1 &

if [ "${USE_GITLAB_LOGGER-0}" -eq 1 ]; then
    /usr/local/bin/gitlab-logger --json /var/log/gitaly
elif command -v xtail >/dev/null; then
    xtail /var/log/gitaly
else
    tail -f /var/log/gitaly/*
fi

wait
