ARG UBI_IMAGE=registry.access.redhat.com/ubi8/ubi

FROM ${UBI_IMAGE}

ADD gitlab-ruby.tar.gz /

COPY scripts/ /scripts

ENV CONFIG_TEMPLATE_DIRECTORY=/etc

RUN dnf --disableplugin=subscription-manager install -by --nodocs ncurses libedit

ENTRYPOINT ["/scripts/entrypoint.sh"]

CMD [ "irb" ]
