ARG CI_REGISTRY_IMAGE=

ARG BUILD_IMAGE=${CI_REGISTRY_IMAGE}/gitlab-ubi-builder:latest

FROM ${BUILD_IMAGE}

ARG DOCUTILS_VERSION=0.11

ADD gitlab-python.tar.gz /

RUN mkdir /assets \
    && pip3 install --compile docutils==${DOCUTILS_VERSION} \
    && cp -R --parents \
        /usr/local/lib/python3.7/site-packages \
        /usr/local/bin/rst2* \
        /assets
