ARG UBI_IMAGE=registry.access.redhat.com/ubi8/ubi:8.1

FROM ${UBI_IMAGE}

ADD kubectl.tar.gz /

RUN chmod +x /usr/local/bin/{kubectl,yq} \
    && dnf clean all \
    && rm -r /var/cache/dnf \
    && dnf install -by --disablerepo="*" --enablerepo="*ubi-8*" --nodocs openssh openssl

# Default to non-root user
USER 65534:65534
