#!/bin/bash
# This script designed to download and verify the sources of GitLab Logger
# Items from environment:
# - GITLAB_LOGGER_SOURCE_URL - complete URL of the source tarball
# - GITLAB_LOGGER_SHA256 - The shasum of the tarball

set -exo pipefail

pushd /build
# Downloads sources
curl --retry 6 -LOsS "${GITLAB_LOGGER_SOURCE_URL}"

# Verify source tarball
echo "${GITLAB_LOGGER_SHA256} $(basename "${GITLAB_LOGGER_SOURCE_URL}")" > SHASUM
sha256sum -c SHASUM
tar xzf "$(basename "${GITLAB_LOGGER_SOURCE_URL}")"

popd # from /build
