#!/bin/bash

set -e

KEYS_DIRECTORY="${KEYS_DIRECTORY:-/etc/ssh}"
SSH_DAEMON="${SSH_DAEMON:-openssh}"

if ls $KEYS_DIRECTORY/ssh_host_* 1> /dev/null 2>&1; then
  echo "Using existing Host Keys"

  if [ "$KEYS_DIRECTORY" != "/etc/ssh" ]; then
    cp $KEYS_DIRECTORY/ssh_host_* "/etc/ssh/"
  fi
else
  echo "Generating Host Keys"

  ssh-keygen -A

  if [ "$KEYS_DIRECTORY" != "/etc/ssh" ]; then
    mkdir -p $KEYS_DIRECTORY
    cp /etc/ssh/ssh_host_* "$KEYS_DIRECTORY/"
  fi
fi


if [ "${SSH_DAEMON}" == "gitlab-sshd" ]; then 
  /srv/gitlab-shell/bin/gitlab-sshd -config-dir /srv/gitlab-shell
else
  if [ "${USE_GITLAB_LOGGER-0}" -eq 1 ]; then
    /usr/local/bin/gitlab-logger /var/log/gitlab-shell &
  else
    if command -v xtail >/dev/null; then
      xtail /var/log/gitlab-shell &
    else
      touch /var/log/gitlab-shell/ssh.log
      tail -f /var/log/gitlab-shell/* &
    fi
  fi

  /usr/sbin/sshd -D -E /var/log/gitlab-shell/ssh.log  
fi
