#!/bin/bash

set -e

touch /var/log/gitlab/workhorse.log

# pre-create known good tmpdir
export TMPDIR=/tmp/gitlab
mkdir -p -m 3770 $TMPDIR

export GITLAB_WORKHORSE_LOG_FILE=${GITLAB_WORKHORSE_LOG_FILE:-stdout}
export GITLAB_WORKHORSE_LOG_FORMAT=${GITLAB_WORKHORSE_LOG_FORMAT:-json}
if [[ "${GITLAB_WORKHORSE_PROM_LISTEN_ADDR}" =~ ^.+:[0-9][0-9]{0,4}$ ]]; then
   export PROM_LISTEN_ADDR="-prometheusListenAddr ${GITLAB_WORKHORSE_PROM_LISTEN_ADDR}"
fi

gitlab-workhorse \
  -logFile ${GITLAB_WORKHORSE_LOG_FILE} \
  -logFormat ${GITLAB_WORKHORSE_LOG_FORMAT} \
  ${GITLAB_WORKHORSE_EXTRA_ARGS} \
  -listenAddr 0.0.0.0:${GITLAB_WORKHORSE_LISTEN_PORT:-8181} \
  -documentRoot "/srv/gitlab/public" \
  -secretPath "/etc/gitlab/gitlab-workhorse/secret" \
  -config "/srv/gitlab/config/workhorse-config.toml" \
  ${PROM_LISTEN_ADDR} \
  2>&1
