#!/bin/bash

set -e

touch /var/log/gitlab/workhorse.log

# pre-create known good tmpdir
export TMPDIR=/tmp/gitlab
mkdir -p -m 3770 $TMPDIR

gitlab-workhorse \
  ${GITLAB_WORKHORSE_EXTRA_ARGS} \
  -listenAddr 0.0.0.0:${GITLAB_WORKHORSE_LISTEN_PORT:-8181} \
  -documentRoot "/srv/gitlab/public" \
  -secretPath "/etc/gitlab/gitlab-workhorse/secret" \
  -config "/srv/gitlab/config/workhorse-config.toml" \
>> /var/log/gitlab/workhorse.log 2>&1 &

if hash xtail 2>/dev/null; then
    xtail /var/log/gitaly
else
    tail -f /var/log/gitaly/*
fi

wait
