ARG UBI_IMAGE=registry.access.redhat.com/ubi8/ubi

FROM ${UBI_IMAGE}

ARG GO_VERSION=1.12.9

RUN cd /usr/local \
    && curl https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz | tar -xz \
    && ln -sf /usr/local/go/bin/* /usr/local/bin
