#!/bin/bash

set -e

ROOT_PASSWORD_FILE="${ROOT_PASSWORD_FILE:-/srv/gitlab/config/initial_root_password}"

if [ -f "${ROOT_PASSWORD_FILE}" ]; then
  export GITLAB_ROOT_PASSWORD=$(cat "${ROOT_PASSWORD_FILE}")
fi

echo "Checking database migrations are up-to-date"

# Seed or migrate the database via gitlab:db:configure
echo "Performing migrations (this will initialized if needed)"
cd /srv/gitlab
/srv/gitlab/bin/rake gitlab:db:configure

echo "Performing custom instance setup"
/scripts/custom-instance-setup
