#!/bin/bash

set -e

ROOT_PASSWORD_FILE="${ROOT_PASSWORD_FILE:-/srv/gitlab/config/initial_root_password}"

if [ -f "${ROOT_PASSWORD_FILE}" ]; then
  export GITLAB_ROOT_PASSWORD=$(cat "${ROOT_PASSWORD_FILE}")
fi

SHARED_RUNNERS_REGISTRATION_TOKEN_FILE="${SHARED_RUNNERS_REGISTRATION_TOKEN_FILE:-/srv/gitlab/config/gitlab_shared_runners_registration_token}"

if [ -f "${SHARED_RUNNERS_REGISTRATION_TOKEN_FILE}" ] && [ -r "${SHARED_RUNNERS_REGISTRATION_TOKEN_FILE}" ]; then
  export GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN=$(cat "${SHARED_RUNNERS_REGISTRATION_TOKEN_FILE}")
fi

echo "Checking database migrations are up-to-date"

# Seed or migrate the database via gitlab:db:configure
echo "Performing migrations (this will initialized if needed)"
cd /srv/gitlab
/srv/gitlab/bin/rake gitlab:db:configure

echo "Performing custom instance setup"
/srv/gitlab/bin/rails runner -e production /scripts/custom-instance-setup
