#!/bin/bash

set -e

echo "Checking Geo database migrations are up-to-date"

cd /srv/gitlab

# Ask for the current DB schema version, via Rake
DB_SCHEMA_VERSION=$(/srv/gitlab/bin/bundle exec rake geo:db:version)
DB_SCHEMA_VERSION=$(echo ${DB_SCHEMA_VERSION} | grep 'Current version: ' | sed -e 's/_//g' -e 's/.* \([[:digit:]]\+\)/\1/')

# If DB_SCHEMA_VERSION is 0, then the database needs initialized
RAKE_TASK="geo:db:migrate"
if [ "${DB_SCHEMA_VERSION}" == "0" ]; then
  echo "Geo Database appears need initialized."
  RAKE_TASK="geo:db:setup"
fi

echo "Performing '${RAKE_TASK}'"
/srv/gitlab/bin/rake ${RAKE_TASK} && STATUS=$? || STATUS=$?

# Attempt to update the FDW
echo "Performing refresh of foreign tables 'geo:db:refresh_foreign_tables'"
/srv/gitlab/bin/rake geo:db:refresh_foreign_tables
