#!/usr/bin/env ruby

require 'bundler/setup'
require 'yaml'
require 'shellwords'

if ARGV.length < 2
  puts <<-HERE
  Usage: rails-pg-env config command

   - config : name of file from /srv/gitlab/config/ to load
   - command: command to pass to exec()
  HERE
  exit 1
end

database_file = "/srv/gitlab/config/#{ARGV.shift}"

# Load configuration yaml, strip 'production'
database_yaml = YAML.load_file(database_file)
config = database_yaml['production']

# dispose of 'adapter'
config.delete 'adapter'

# move a few keys to align to PG environment variablenaming
config['user'] = config.delete 'username'
config['clientencoding'] = config.delete 'encoding'

config.each { |key, value|
  ENV["PG#{key.upcase}"]="#{value}"
}

exec ARGV.shelljoin
