#!/usr/bin/env ruby

require 'bundler/setup'
require 'yaml'
require 'redis'

def ping_redis(config)
  had_error = false
  begin
    # configure the Redis client
    redis = Redis.new(config)
    print "- Attempting to connect to '#{redis._client.scheme}://#{redis._client.host}:#{redis._client.port}' "
    # "ping" the server
    redis.ping
  rescue RuntimeError => e
    puts "FAILURE"
    puts "  ERROR: #{e.message}"
    had_error = true
  else
    # nicely disconnect
    redis.disconnect!
    puts "SUCCESS"
    had_error = false
  end
end


checks_passed = 0
Dir.chdir("/srv/gitlab/config")
files = Dir.glob(["resque.yml", "redis\..*.yml"])
files.each { |resque_file|
  resque_yaml = YAML.load_file(resque_file)
  puts "Checking '#{resque_file}'"
  success = ping_redis(resque_yaml["production"])
  checks_passed += 1 if success
}

exit (checks_passed == files.count ? 0 : 1)
